name: Flask CI/CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: 10.246.127.193:5000
  IMAGE_NAME: flask-lab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY \
            -u "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest
